# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJ0GF2AdNyIU0I7Exju1lgth4SbCyyNy
"""

###Creating your own dataset from Google Images
###Create directory and upload urls files into my server
from fastai import *
from fastai.vision import *

###Get a list of URLs
##Go to Google Images and search for the images you are interested in.
##Download into file
# urls=Array.from(document.querySelectorAll('.rg_i')).map(el=> el.hasAttribute('data-src')?el.getAttribute('data-src'):el.getAttribute('data-iurl'));
# window.open('data:text/csv;charset=utf-8,' + escape(urls.join('\n')));

##Create directory and upload urls file into your server
folder = 'black'
file = 'black_bears.txt'

folder = 'grizzly'
file = 'brown_bears.txt'

folder = 'teddys'
file = 'teddys.txt'

path = Path('data/bears')
dest = path/folder
dest.mkdir(parents=True , exist_ok=True)

##Download images
classes = ['teddys' , 'grizzly' , 'black']

download_images(path/file,dest, max_pics=200)

for c in classes:
  print(c)
  verify_images(path/c, delete=True, max_workers=8)

##View data
np.random.seed(42)
data = ImageDataBunch.from_folder(path, train=".", valid_pct=0.2,
       ds_tfms=get_transforms(), size=224, num_workers=4).normalize(imagenet_stats)

data.classes

data.show_batch(rows=3, figsize=(7,8))

